-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")
--
-- -- 当光标悬停 (CursorHold) 时，自动显示诊断浮窗
-- vim.api.nvim_create_autocmd("CursorHold", {
--   callback = function()
--     vim.diagnostic.open_float(nil, {
--       focusable = false, -- 浮窗不可聚焦（防止干扰打字）
--       close_events = { "BufLeave", "CursorMoved", "InsertEnter", "FocusLost" },
--       source = "always", -- 显示错误来源（如 cppcheck/clangd）
--       prefix = " ",
--       scope = "cursor",
--     })
--   end,
-- })
